/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test public void testRoll() {
        int n = 10;
        assertEquals("Returned array length should be equal to the n parameter passed in", n, Library.roll(n).length);
    }

    @Test public void testContainsDuplicates() {
        int[] testArray = {1,2,3,4,4,6,7,8,9,10};
        assertTrue("Should return true", Library.containsDuplicates(testArray));
    }

    @Test public void testContainsDuplicates2() {
        int[] testArray = {1,2,3,4,5,6,7,8,9,10};
        assertFalse("Should return false", Library.containsDuplicates(testArray));
    }

    @Test public void testCalculateAverage() {
        int[] testArray = {97,15,43,50,31,100};
        int testValue = 56;
        assertEquals("Returned value should be 56", testValue, Library.calculateAverage(testArray));
    }

    @Test public void testgetLowestAverageOf() {
        int[][] testArray = {
                {16, 96, 9, 56, 44, 93, 92},
                {58, 47, 6, 37, 44, 83, 82},
                {77, 67, 1, 82, 44, 1, 72},
                {90, 88, 34, 68, 44, 93, 62}
        };

        assertArrayEquals("Arrays should be the same", testArray[2], Library.lowestAverage(testArray));
    }
}
