import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Restaurant {
    public static void main(String args[]) {
        Restaurant chilis = new Restaurant("Chili's","$$");
        chilis.addReview(new Review("This place is GREAT!", 1, "Evan Slaton"));
        chilis.addReview(new Review("This place is the WORST", 100, "Notals Nave"));

        System.out.println(chilis.toString());
    }

    // Instance properties
    private String name;
    protected int rating;
    private String priceCategory;
    private LinkedList<Review> reviews;
    private List<Integer> starRatings;

    // Constructor
    Restaurant(String name, String priceCategory) {
        this.name = name;
        this.rating = -1;
        this.priceCategory = priceCategory;
        this.reviews = new LinkedList();
        this.starRatings = new ArrayList<>();
    }

    // Returns a string with this instance of the Restaurant's info
    public String toString() {
        String ratings;
        if (rating == -1) {
            ratings = "No rating yet";
        } else {
            ratings = String.valueOf(this.rating);
        }
        String aboutRestaurant = "Name: " + this.name + ", Star Rating: " + ratings + ", Price Category: " + this.priceCategory + "\n";
        for (Review review : reviews) {
            aboutRestaurant += review.toString() + "\n";
        }
        return aboutRestaurant;
    }

    // Adds a review to this instance of the Restaurant's reviews
    public void addReview(Review review) {
        reviews.add(review);
        updateRestaurantStars(review.getStars());
    }

    // Updates this instance of the Restaurant's star rating
    protected void updateRestaurantStars(int stars) {
        this.starRatings.add(stars);
        Integer total = 0;
        for (Integer star : starRatings) {
            total += star;
        }
        this.rating = total / starRatings.size();
    }
}
