/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import java.nio.file.Path;
import java.nio.file.Paths;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testLinterOnGates() {
        Path testFile = Paths.get("resources/gates.js");
        assertEquals("Should return 46", 46, App.linter(testFile));
    }

    @Test public void testLinterOnNoErrors() {
        Path testFile = Paths.get("resources/no-errors.js");
        assertEquals("Should return 0", 0, App.linter(testFile));
    }

    @Test public void testLinterOnOneError() {
        Path testFile = Paths.get("resources/one-error.js");
        assertEquals("Should return 1", 1, App.linter(testFile));
    }

    @Test public void testLinterOnFewErrors() {
        Path testFile = Paths.get("resources/few-errors.js");
        assertEquals("Should return 3", 3, App.linter(testFile));
    }

    @Test public void testLinterOnManyError() {
        Path testFile = Paths.get("resources/many-errors.js");
        assertEquals("Should return 10", 10, App.linter(testFile));
    }

    @Test public void testLinterOnEmptyFile() {
        Path testFile = Paths.get("resources/empty.js");
        assertEquals("Should return 0", 0, App.linter(testFile));
    }
}