import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {

    String input = "C:/Users/evans/Desktop/test.BMP";
    String output = "C:/Users/evans/Desktop/test.BMP";
    String transform = "rotate";
    BufferedImage image = readBitmap(input);
    Bitmap bitmap = new Bitmap(input, output, transform, image);

    writeBitmap((bitmap.image));

    }

    public static BufferedImage readBitmap(String inputFilePath) {
        BufferedImage image = null;
        try {
            image = ImageIO.read(new File(inputFilePath));
        } catch (IOException error) {
            System.out.println(error);
        }
        return image;
    }

    public static void writeBitmap(BufferedImage image) {
        try {
            ImageIO.write(image, "BMP", new File("C:/Users/evans/Desktop/test2.BMP"));
        } catch (IOException error) {
            System.out.println(error);
        }
    }
}
