import java.io.BufferedReader;
import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {


read();
//        System.out.println(new App().getGreeting());
    }

    public static void read() {
        // read the book (details, paths)
        // determine if line is missing a ; (empty lines don't count)
        // print an error whenever it finds a line that doesn’t end in a semi-colon.
        Charset charset = Charset.forName("US-ASCII");
        try (BufferedReader reader = Files.newBufferedReader(FileSystems.getDefault().getPath("resources", "gates.js"), charset)) {
            String currentLine = "";
            while (currentLine != null) {
                System.out.println(currentLine);
                currentLine = reader.readLine();
            }
        } catch(IOException error) {
            System.out.println(error);
        }
    }

}
