import java.io.BufferedReader;
import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        Path fileToLinter = Paths.get("resources/gates.js");
        linter(fileToLinter);
    }

    // Prints which lines are missing a semicolon to the console
    // Excludes lines that are empty, end in '{' or '}' and/or contain 'if' and/or 'else'
    public static int linter(Path fileToLinter) {
        Charset charset = Charset.forName("US-ASCII");
        int numberOfErrors = 0;
        try (BufferedReader reader = Files.newBufferedReader(fileToLinter, charset)) {
            String currentLine = "";
            int lineNumber = 0;

            while (currentLine != null) {
                if(!currentLine.isEmpty()
                    && !currentLine.endsWith("{")
                    && !currentLine.endsWith("}")
                    && !currentLine.contains("if")
                    && !currentLine.contains("else")
                    && !currentLine.endsWith(";"))
                {
                    System.out.println("Line " + lineNumber + " needs a semicolon");
                    numberOfErrors++;
                }
                currentLine = reader.readLine();
                lineNumber++;

            }
        } catch(IOException error) {
            System.out.println(error);
        }
        return numberOfErrors;
    }
}
